### ISSUE TITLE
screen dies during playback

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/deadstream#133]
```
Oct 05 09:10:21 deadstream2 bash[16090]: 2021-10-05 09:10:21.437 INFO: timemachine.main in track event callback playlist-pos, 2
Oct 05 09:19:00 deadstream2 bash[16090]: 2021-10-05 09:19:00.546 INFO: timemachine.main in track event callback playlist-pos, 3
Oct 05 09:19:54 deadstream2 bash[16090]: Traceback (most recent call last):
Oct 05 09:19:54 deadstream2 bash[16090]:   File "/home/deadhead/env_20211005.5e2f4ec3/bin/timemachine", line 10, in <module>
Oct 05 09:19:54 deadstream2 bash[16090]:     sys.exit(main())
Oct 05 09:19:54 deadstream2 bash[16090]:   File "/home/deadhead/env_20211005.5e2f4ec3/lib/python3.7/site-packages/timemachine/main.py", line 946, in main
Oct 05 09:19:54 deadstream2 bash[16090]:     eloop.run()
Oct 05 09:19:54 deadstream2 bash[16090]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Oct 05 09:19:54 deadstream2 bash[16090]: 2021-10-05 09:19:54.377 INFO: timemachine.main Pausing on player
Oct 05 09:19:54 deadstream2 bash[16090]: 2021-10-05 09:19:54.377 INFO: timemachine.GD pausing
Oct 05 10:14:18 deadstream2 bash[16090]:     self._target(*self._args, **self._kwargs)
Oct 05 10:14:18 deadstream2 bash[16090]:   File "/home/deadhead/env_20211005.5e2f4ec3/lib/python3.7/site-packages/timemachine/main.py", line 725, in event_loop
Oct 05 10:14:18 deadstream2 bash[16090]:     if current['ON_TOUR'] and current['TOUR_STATE'] != config.PLAYING:
Oct 05 10:14:18 deadstream2 bash[16090]: KeyError: 'ON_TOUR'
Oct 05 10:14:18 deadstream2 bash[16090]: 2021-10-05 10:14:18.498 INFO: timemachine.GD Running update
Oct 05 10:14:39 deadstream2 bash[16090]: 2021-10-05 10:14:39.398 DEBUG: urllib3.connectionpool Starting new HTTPS connection (1): archive.org:443
```

**Comment by eichblatt** [comment]
I think that this is happening now because the auto-updater (from the archive) is happening concurrently. While the GDArchive object is being re-written, this process fails.

There are 2 solutions to this: 

1. Update the archive as part of the event loop, possibly only by user request (eg, press the "year" button while in experience mode)
2. Use a lock in the GDArchive_updater and in the event loop.
